<a href="https://colab.research.google.com/github/satyamkarn100-ctrl/Neural-Recommendation-Personalization-Engine/blob/main/01_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import os
!rm -rf /content/drive
from google.colab import drive
drive.mount('/content/drive')

rm: cannot remove '/content/drive/.shortcut-targets-by-id': Operation canceled
rm: cannot remove '/content/drive/MyDrive': Operation canceled
rm: cannot remove '/content/drive/.Trash-0': Directory not empty
rm: cannot remove '/content/drive/.Encrypted/.shortcut-targets-by-id': Operation canceled
rm: cannot remove '/content/drive/.Encrypted/MyDrive': Operation canceled
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
!pip install -q huggingface_hub
from huggingface_hub import login,HfApi
login()

In [3]:
# !pip install -q pandas==2.2.3
# !pip -q install -U huggingface_hub pandas pyarrow
# !pip install datasets faiss-cpu polars -q

In [12]:
!pip install -U datasets huggingface_hub

Requirement already satisfied: datasets in /usr/local/lib/python3.13/dist-packages (5.0.1)
Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.13/dist-packages (1.32.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets) (3.32.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.1.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.13/dist-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.6.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2025.12.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets) (1.24.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [5]:
url = "https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/benchmark/5core/rating_only/Electronics.csv"
reviews = pd.read_csv(url)

print("Shape:", reviews.shape)
reviews.head()

Shape: (15473536, 4)

                        user_id parent_asin  rating      timestamp
0  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B0047T79VS     3.0  1344406083000
1  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01HHURN3W     3.0  1408995743000
2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B00L0YLRUW     1.0  1439226089000
3  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B017T99JPG     5.0  1456772365000
4  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01LW71IBJ     5.0  1456772571000

In [6]:
print('Shape:',reviews.shape,'\n\n')
print('Columns:')
print(reviews.columns.tolist(),'\n')
print('Data Types:',reviews.dtypes,'\n')
print('Missing Values:',reviews.isna().sum())
print('\nDuplicate Rows:',reviews.duplicated().sum())
print('\n Rating Distribution',reviews['rating'].value_counts().sort_index())

print("\nUnique Users:", reviews["user_id"].nunique())
print("Unique Products:", reviews["parent_asin"].nunique())

display(reviews.head())

Shape: (15473536, 4)


Columns:
['user_id', 'parent_asin', 'rating', 'timestamp']

Data Types: user_id         object
parent_asin     object
rating         float64
timestamp        int64
dtype: object

Missing Values: user_id        0
parent_asin    0
rating         0
timestamp      0
dtype: int64

Duplicate Rows: 0

 Rating Distribution rating
1.0     1287788
2.0      713558
3.0     1074820
4.0     2190347
5.0    10207023
Name: count, dtype: int64

Unique Users: 1641026
Unique Products: 368228

                        user_id parent_asin  rating      timestamp
0  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B0047T79VS     3.0  1344406083000
1  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01HHURN3W     3.0  1408995743000
2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B00L0YLRUW     1.0  1439226089000
3  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B017T99JPG     5.0  1456772365000
4  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01LW71IBJ     5.0  1456772571000

In [2]:
meta1 = pd.read_parquet("https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw_meta_Electronics/full-00000-of-00010.parquet")

meta2 = pd.read_parquet("https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw_meta_Electronics/full-00001-of-00010.parquet")

meta3 = pd.read_parquet("https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw_meta_Electronics/full-00002-of-00010.parquet")

meta4 = pd.read_parquet("https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw_meta_Electronics/full-00003-of-00010.parquet")

meta5 = pd.read_parquet("https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw_meta_Electronics/full-00004-of-00010.parquet")

meta6 = pd.read_parquet("https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw_meta_Electronics/full-00005-of-00010.parquet")

meta7 = pd.read_parquet("https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw_meta_Electronics/full-00006-of-00010.parquet")

meta8 = pd.read_parquet("https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw_meta_Electronics/full-00007-of-00010.parquet")

meta9 = pd.read_parquet("https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw_meta_Electronics/full-00008-of-00010.parquet")

meta10 = pd.read_parquet("https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw_meta_Electronics/full-00009-of-00010.parquet")

In [3]:
for df in [meta1, meta2, meta3, meta4, meta5,
           meta6, meta7, meta8, meta9, meta10]:

    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print(df.dtypes)
    print(df.head())
    print("-" * 80)

Shape: (161002, 16)
Columns: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together', 'subtitle', 'author']
main_category       object
title               object
average_rating     float64
rating_number        int64
features            object
description         object
price               object
images              object
videos              object
store               object
categories          object
details             object
parent_asin         object
bought_together     object
subtitle            object
author              object
dtype: object
               main_category  \
0            All Electronics
1            All Electronics
2                  Computers
3             AMAZON FASHION
4  Cell Phones & Accessories

                                               title  average_rating  \
0             FS-1051 FATSHARK TELEPORTER V3 HEADSET             3.5
1                      Ce-H22B12-S1 4Kx2K Hdmi 4Port             5.0
2  Digi-Tatoo Decal Skin Compatible With MacBook ...             4.5
3  NotoCity Compatible with Vivoactive 4 band 22m...             4.5
4             Motorola Droid X Essentials Combo Pack             3.8

   rating_number                                           features  \
0              6                                                 []
1              1             [UPC: 662774021904, Weight: 0.600 lbs]
2            246  [WARNING: Please IDENTIFY MODEL NUMBER on the ...
3            233  [☛NotoCity 22mm band is designed for Vivoactiv...
4             64  [New Droid X Essentials Combo Pack, Exclusive ...

                                         description  price  \
0  [Teleporter V3 The “Teleporter V3” kit sets a ...   None
1                               [HDMI In - HDMI Out]   None
2                                                 []  19.99
3                                                 []   9.99
4  [all Genuine High Quality Motorola Made Access...  14.99

                                              images  \
0  {'hi_res': [None], 'large': ['https://m.media-...
1  {'hi_res': ['https://m.media-amazon.com/images...
2  {'hi_res': ['https://m.media-amazon.com/images...
3  {'hi_res': ['https://m.media-amazon.com/images...
4  {'hi_res': [None, None, None, None, None], 'la...

                                              videos       store  \
0            {'title': [], 'url': [], 'user_id': []}   Fat Shark
1            {'title': [], 'url': [], 'user_id': []}        SIIG
2  {'title': ['AL 2Sides Video', 'MacBook Protect...  Digi-Tatoo
3            {'title': [], 'url': [], 'user_id': []}    NotoCity
4            {'title': [], 'url': [], 'user_id': []}     Verizon

                                          categories  \
0   [Electronics, Television & Video, Video Glasses]
1  [Electronics, Television & Video, Accessories,...
2  [Electronics, Computers & Accessories, Laptop ...
3  [Electronics, Wearable Technology, Clips, Arm ...
4  [Electronics, Computers & Accessories, Compute...

                                             details parent_asin  \
0  {"Date First Available": "August 2, 2014", "Ma...  B00MCW7G9M
1  {"Product Dimensions": "0.83 x 4.17 x 2.05 inc...  B00YT6XQSE
2  {"Brand": "Digi-Tatoo", "Color": "Fresh Marble...  B07SM135LS
3  {"Date First Available": "May 29, 2020", "Manu...  B089CNGZCW
4  {"Product Dimensions": "11.6 x 6.9 x 3.1 inche...  B004E2Z88O

  bought_together subtitle author
0            None     None   None
1            None     None   None
2            None     None   None
3            None     None   None
4            None     None   None
--------------------------------------------------------------------------------
Shape: (161002, 16)
Columns: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together', 'subtitle', 'author']
main_category       object
title               object
average_rating     float64
rating_number        int64
features            object
description         object
price               object
images              object
videos              object
store               object
categories          object
details             object
parent_asin         object
bought_together     object
subtitle            object
author              object
dtype: object
          main_category                                              title  \
0       All Electronics  The California Raisins Band includes Lead Sing...
1  Home Audio & Theater  Earbuds with Microphone Mic Noise Isolating Ea...
2        Camera & Photo  Sony Alpha NEX-7 Digital Camera Body & E 18-55...
3             Computers  Team T-Force Vulcan 16GB (2 x 8GB) 288-Pin DDR...
4  Home Audio & Theater  Monster M Series M1.2s MLock Master Pin Center...

   average_rating  rating_number  \
0             4.8             10
1             4.1             50
2             5.0              1
3             4.6             24
4             4.0              3

                                            features  \
0                                                 []
1                                                 []
2                                                 []
3                                                 []
4  [UL CL3-Rated for in-wall use., Deep bass, ext...

                                         description price  \
0  [The California Raisins Band includes Lead Sin...  None
1                                                 []  None
2                                                 []  None
3                                                 []  None
4  [From the Manufacturer, Advanced Performance S...  None

                                              images  \
0  {'hi_res': ['https://m.media-amazon.com/images...
1  {'hi_res': ['https://m.media-amazon.com/images...
2  {'hi_res': [None, None, None, None, None, None...
3  {'hi_res': ['https://m.media-amazon.com/images...
4  {'hi_res': ['https://m.media-amazon.com/images...

                                              videos                   store  \
0            {'title': [], 'url': [], 'user_id': []}  The California Raisins
1            {'title': [], 'url': [], 'user_id': []}                   Gsebr
2            {'title': [], 'url': [], 'user_id': []}                    Sony
3  {'title': ['T-Force VULCAN Video'], 'url': ['h...               TEAMGROUP
4            {'title': [], 'url': [], 'user_id': []}                 Monster

                                          categories  \
0                                                 []
1  [Electronics, Headphones, Earbuds & Accessorie...
2     [Electronics, Camera & Photo, Digital Cameras]
3  [Electronics, Computers & Accessories, Compute...
4  [Electronics, Television & Video, Accessories,...

                                             details parent_asin  \
0  {"Package Dimensions": "7.13 x 2.6 x 2.13 inch...  B003YTGP6C
1  {"Manufacturer": "Gsebr", "Date First Availabl...  B088R7L6KS
2  {"Brand": "Sony", "Maximum Focal Length": "55 ...  B00DQW06GC
3  {"Product Dimensions": "5.51 x 0.28 x 1.26 inc...  B06W2LL3T5
4  {"Product Dimensions": "120 x 1 x 1 inches", "...  B000CC5PE2

  bought_together subtitle author
0            None     None   None
1            None     None   None
2            None     None   None
3            None     None   None
4            None     None   None
--------------------------------------------------------------------------------
Shape: (161001, 16)
Columns: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together', 'subtitle', 'author']
main_category       object
title               object
average_rating     float64
rating_number        int64
features            object
description         object
price               object
images              object
videos              object
store               object
categories          object
details             object
parent_asin         object
bought_together     object
subtitle            object
author              object
dtype: object
    main_category                                              title  \
0  Camera & Photo  OdiySurveil(TM) Universal Wall Ceiling Metal W...
1  Camera & Photo  Foscam FI9961EP Full HD 1080P @ 25fps PoE Vand...
2  Camera & Photo  Tamrac T1500 Nagano 12 Backpack for Camera - Blue
3     Amazon Home  5.9 x 3.6 Feet Day of the Dead Banner Backdrop...
4  Camera & Photo  Comwinn TPU Woven Leather Texture Breathable D...

   average_rating  rating_number  \
0             3.9             87
1             3.8             51
2             4.5              3
3             4.4             22
4             4.7             13

                                            features  \
0  [★★★★★ APPLICATION: application for Indoor Out...
1  [Full HD 1080P Resolution 1920*1080 at 25fps o...
2  [Holds an 11" laptop or tablet, lenses up to 4...
3  [Day of the Dead Halloween Decorations: there ...
4                                                 []

                                         description price  \
0  [Description:, 100% brand new ; It is construc...  8.54
1                                                 []  None
2  [Product Description, An outdoor-focused pack,...  None
3  [Features: You can give this Day of the Dead d...  None
4                                                 []  None

                                              images  \
0  {'hi_res': ['https://m.media-amazon.com/images...
1  {'hi_res': ['https://m.media-amazon.com/images...
2  {'hi_res': ['https://m.media-amazon.com/images...
3  {'hi_res': ['https://m.media-amazon.com/images...
4  {'hi_res': ['https://m.media-amazon.com/images...

                                              videos  \
0            {'title': [], 'url': [], 'user_id': []}
1  {'title': ['Foscam AI Human Detection', 'How t...
2  {'title': ['Avnil Series of Backpacks', 'Lowep...
3  {'title': [' The Dead Tablecloth'], 'url': ['h...
4            {'title': [], 'url': [], 'user_id': []}

                       store  \
0  Overseasymall OdiySurveil
1                     FOSCAM
2                     Tamrac
3                    Remerry
4              Cable Matters

                                          categories  \
0  [Electronics, Security & Surveillance, Accesso...
1  [Electronics, Camera & Photo, Video Surveillan...
2  [Electronics, Camera & Photo, Bags & Cases, Ca...
3  [Electronics, Camera & Photo, Lighting & Studi...
4  [Electronics, Computers & Accessories, Compute...

                                             details parent_asin  \
0  {"Product Dimensions": "2.8 x 2 x 0.6 inches",...  B01GVM83JU
1  {"Package Dimensions": "8.1 x 6.7 x 4.9 inches...  B07V354SXS
2  {"Product Dimensions": "6.69 x 9.06 x 21.26 in...  B01M5CZDXE
3  {"Product Dimensions": "70.87\"L x 43.31\"W", ...  B0B4DVSHTM
4  {"Package Dimensions": "8.2 x 6.2 x 1.6 inches...  B00DUYE7H0

  bought_together subtitle author
0            None     None   None
1            None     None   None
2            None     None   None
3            None     None   None
4            None     None   None
--------------------------------------------------------------------------------
Shape: (161001, 16)
Columns: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together', 'subtitle', 'author']
main_category       object
title               object
average_rating     float64
rating_number        int64
features            object
description         object
price               object
images              object
videos              object
store               object
categories          object
details             object
parent_asin         object
bought_together     object
subtitle            object
author              object
dtype: object
               main_category  \
0             Camera & Photo
1             Camera & Photo
2             Camera & Photo
3            All Electronics
4  Cell Phones & Accessories

                                               title  average_rating  \
0  ePhoto T69green/bag Continuous Lighting Green ...             3.5
1   Recharger Li-ion Battery for PANASONIC VW-VBK180             1.0
2  3.7V 1400mAh NP-BG1/FG1 Replacement Battery Fo...             5.0
3  NH407UP Replace Remote Control fit for Magnavo...             4.9
4  Huaxia Datacom Deluxe Blue 3 part Hard Skin Ca...             4.2

   rating_number                                           features  \
0             46  [2 x 7ft light stands/2 x 45w Perfect daylight...
1              3                                                 []
2              2                                                 []
3             24  [AIDITIYMI NH407UP Replacement IR Remote Contr...
4            934  [Touch 4th Generation, Black Hard / Blue Skin,...

                                         description price  \
0  [Our support system is constructed from lightw...  None
1                                                 []  None
2                                                 []  None
3  [AIDITIYMI NH407UP Replaced Remote Control wor...  19.6
4  [Practical design allows easy access to all bu...  None

                                              images  \
0  {'hi_res': [None, None, None, None], 'large': ...
1  {'hi_res': [None, None, None, None, None], 'la...
2  {'hi_res': ['https://m.media-amazon.com/images...
3  {'hi_res': ['https://m.media-amazon.com/images...
4  {'hi_res': ['https://m.media-amazon.com/images...

                                              videos       store  \
0            {'title': [], 'url': [], 'user_id': []}      ePhoto
1            {'title': [], 'url': [], 'user_id': []}  Crazy Cart
2            {'title': [], 'url': [], 'user_id': []}      Neewer
3  {'title': ['Quick and Honest Review of Magnavo...   AIDITIYMI
4            {'title': [], 'url': [], 'user_id': []}      Deluxe

                                          categories  \
0  [Electronics, Camera & Photo, Lighting & Studi...
1                                                 []
2  [Electronics, Camera & Photo, Accessories, Bat...
3  [Electronics, Television & Video, Accessories,...
4  [Electronics, Portable Audio & Video, MP3 & MP...

                                             details parent_asin  \
0  {"Product Dimensions": "36 x 8 x 8 inches", "I...  B0035GT2SC
1  {"Package Dimensions": "1.57 x 1.18 x 0.79 inc...  B006N24TG0
2  {"Auto Focus Technology": "Phase Detection", "...  B0081CX9DY
3  {"Product Dimensions": "7 x 2 x 0.6 inches", "...  B0825ZLCZV
4  {"Product Dimensions": "5.5 x 4.3 x 0.9 inches...  B008BR4L2W

  bought_together subtitle author
0            None     None   None
1            None     None   None
2            None     None   None
3            None     None   None
4            None     None   None
--------------------------------------------------------------------------------
Shape: (161001, 16)
Columns: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together', 'subtitle', 'author']
main_category       object
title               object
average_rating     float64
rating_number        int64
features            object
description         object
price               object
images              object
videos              object
store               object
categories          object
details             object
parent_asin         object
bought_together     object
subtitle            object
author              object
dtype: object
               main_category  \
0                  Computers
1       Home Audio & Theater
2                  Computers
3  Cell Phones & Accessories
4                  Computers

                                               title  average_rating  \
0  Sunrise Alarm Clock- Wake up Light LED Clock S...             5.0
1  Logitech 980000417 Z130 Compact 2.0 Stereo Spe...             4.3
2  Asus LCD MX279H LED Backlight 27inch Wide IPS ...             1.0
3  iPad Case, iPad 2/3/4 Case, HAOCOO Stylish Art...             4.3
4  Laptop Case FOPATI Laptop Sleeve Case 13.3 14 ...             4.8

   rating_number                                           features  \
0              3  [🌞Simulate a natural Sunrise & Sunset: this su...
1           1857  [Sold as 1 Each., Five watts of total power fo...
2              1  [1920x1080 Resolution; 0.311mm Pixel Pitch; 25...
3             14                                                 []
4             49  [Simple but meet your every needs. Slim, porta...

                                         description  price  \
0  [What makes it so much better? 1. Unlike Roku ...   None
1  [With convenient controls and easy setup, the ...  28.95
2  [27IN HD 1920X1080 AH-IPS MX279H 16:9 HDMI VGA...   None
3                                                 []   None
4                                                 []   None

                                              images  \
0  {'hi_res': ['https://m.media-amazon.com/images...
1  {'hi_res': ['https://m.media-amazon.com/images...
2  {'hi_res': ['https://m.media-amazon.com/images...
3  {'hi_res': ['https://m.media-amazon.com/images...
4  {'hi_res': ['https://m.media-amazon.com/images...

                                              videos     store  \
0            {'title': [], 'url': [], 'user_id': []}     ANTOP
1  {'title': ['Honest Review of Logitech PC Speak...  Logitech
2            {'title': [], 'url': [], 'user_id': []}      ASUS
3            {'title': [], 'url': [], 'user_id': []}    HAOCOO
4  {'title': ['FOPATI laptop sleeve'], 'url': ['h...    FOPATI

                                          categories  \
0                                                 []
1  [Electronics, Computers & Accessories, Compute...
2   [Electronics, Computers & Accessories, Monitors]
3  [Electronics, Computers & Accessories, Tablet ...
4  [Electronics, Computers & Accessories, Laptop ...

                                             details parent_asin  \
0  {"Brand": "ANTOP", "Color": "White-173", "Disp...  B01D868TXC
1  {"Product Dimensions": "3.96 x 5.58 x 4.34 inc...  B003FRXFWK
2  {"Standing screen display size": "27 Inches", ...  B00MZ44MMG
3  {"Package Dimensions": "10.6 x 7.8 x 0.8 inche...  B07F3636ZD
4  {"Standing screen display size": "15.6 Inches"...  B081W4SMWD

  bought_together subtitle author
0            None     None   None
1            None     None   None
2            None     None   None
3            None     None   None
4            None     None   None
--------------------------------------------------------------------------------
Shape: (161001, 16)
Columns: ['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together', 'subtitle', 'author']
main_category       object
title               object
average_rating     float64
rating_number        int64
features            object
description         object
price               object
images              object
videos              object
store               object
categories          object
details             object
parent_asin         object
bought_together     object
subtitle            object
author              object
dtype: object
               main_category  \
0             Camera & Photo
1    Industrial & Scientific
2            All Electronics
3  Cell Phones & Accessories
4                  Computers

                                               title  average_rating  \
0  Tripod Reducer 3/8" to 1/4" 50mm Diameter Moun...             3.9
1  Extra Long Lightning Cable [Apple MFi Certifie...             4.2

In [4]:
for df in [meta1, meta2, meta3, meta4, meta5,
           meta6, meta7, meta8, meta9, meta10]:

    print(df.isna().sum())
    print("-" * 80)

main_category        1642
title                   0
average_rating          0
rating_number           0
features                0
description             0
price                   0
images                  0
videos                  0
store                 890
categories              0
details                 0
parent_asin             0
bought_together    161002
subtitle           160940
author             160965
dtype: int64
--------------------------------------------------------------------------------
main_category        1351
title                   0
average_rating          0
rating_number           0
features                0
description             0
price                   0
images                  0
videos                  0
store                 888
categories              0
details                 0
parent_asin             0
bought_together    161002
subtitle           160906
author             160957
dtype: int64
--------------------------------------------------------------------------------
main_category        1306
title                   0
average_rating          0
rating_number           0
features                0
description             0
price                   0
images                  0
videos                  0
store                 870
categories              0
details                 0
parent_asin             0
bought_together    161001
subtitle           160919
author             160955
dtype: int64
--------------------------------------------------------------------------------
main_category        1275
title                   0
average_rating          0
rating_number           0
features                0
description             0
price                   0
images                  0
videos                  0
store                 943
categories              0
details                 0
parent_asin             0
bought_together    161001
subtitle           160924
author             160951
dtype: int64
--------------------------------------------------------------------------------
main_category        2011
title                   0
average_rating          0
rating_number           0
features                0
description             0
price                   0
images                  0
videos                  0
store                 969
categories              0
details                 0
parent_asin             0
bought_together    161001
subtitle           160904
author             160951
dtype: int64
--------------------------------------------------------------------------------
main_category        1239
title                   0
average_rating          0
rating_number           0
features                0
description             0
price                   0
images                  0
videos                  0
store                 942
categories              0
details                 0
parent_asin             0
bought_together    161001
subtitle           160905
author             160951
dtype: int64
--------------------------------------------------------------------------------
main_category        1557
title                   0
average_rating          0
rating_number           0
features                0
description             0
price                   0
images                  0
videos                  0
store                 940
categories              0
details                 0
parent_asin             0
bought_together    161001
subtitle           160919
author             160938
dtype: int64
--------------------------------------------------------------------------------
main_category       11808
title                   0
average_rating          0
rating_number           0
features                0
description             0
price                   0
images                  0
videos                  0
store                 963
categories              0
details                 0
parent_asin             0
bought_together    161001
subtitle           160945
author             160951
dtype: int64
--------------------------------------------------------------------------------
main_category       20522
title                   0
average_rating          0
rating_number           0
features                0
description             0
price                   0
images                  0
videos                  0
store                1034
categories              0
details                 0
parent_asin             0
bought_together    161001
subtitle           160907
author             160959
dtype: int64
--------------------------------------------------------------------------------
main_category       63623
title                   0
average_rating          0
rating_number           0
features                0
description             0
price                   0
images                  0
videos                  0
store                1081
categories              0
details                 0
parent_asin             0
bought_together    161001
subtitle           160892
author             160958
dtype: int64
--------------------------------------------------------------------------------

In [5]:
meta1.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Electronics,FS-1051 FATSHARK TELEPORTER V3 HEADSET,3.5,6,[],[Teleporter V3 The “Teleporter V3” kit sets a ...,None,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Fat Shark,"[Electronics, Television & Video, Video Glasses]","{""Date First Available"": ""August 2, 2014"", ""Ma...",B00MCW7G9M,None,None,None
1,All Electronics,Ce-H22B12-S1 4Kx2K Hdmi 4Port,5.0,1,"[UPC: 662774021904, Weight: 0.600 lbs]",[HDMI In - HDMI Out],None,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",SIIG,"[Electronics, Television & Video, Accessories,...","{""Product Dimensions"": ""0.83 x 4.17 x 2.05 inc...",B00YT6XQSE,None,None,None
2,Computers,Digi-Tatoo Decal Skin Compatible With MacBook ...,4.5,246,[WARNING: Please IDENTIFY MODEL NUMBER on the ...,[],19.99,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': ['AL 2Sides Video', 'MacBook Protect...",Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop ...","{""Brand"": ""Digi-Tatoo"", ""Color"": ""Fresh Marble...",B07SM135LS,None,None,None
3,AMAZON FASHION,NotoCity Compatible with Vivoactive 4 band 22m...,4.5,233,[☛NotoCity 22mm band is designed for Vivoactiv...,[],9.99,{'hi_res': ['https://m.media-amazon.com/images...,"{'title': [], 'url': [], 'user_id': []}",NotoCity,"[Electronics, Wearable Technology, Clips, Arm ...","{""Date First Available"": ""May 29, 2020"", ""Manu...",B089CNGZCW,None,None,None
4,Cell Phones & Accessories,Motorola Droid X Essentials Combo Pack,3.8,64,"[New Droid X Essentials Combo Pack, Exclusive ...",[all Genuine High Quality Motorola Made Access...,14.99,"{'hi_res': [None, None, None, None, None], 'la...","{'title': [], 'url': [], 'user_id': []}",Verizon,"[Electronics, Computers & Accessories, Compute...","{""Product Dimensions"": ""11.6 x 6.9 x 3.1 inche...",B004E2Z88O,None,None,None

In [14]:
metadata_dfs = [meta1, meta2, meta3, meta4, meta5,meta6, meta7, meta8, meta9, meta10]

# drop_cols = ["images","videos","bought_together","subtitle","author",'price']
drop_cols = ['price']
for df in metadata_dfs:
    df.drop(columns=drop_cols, inplace=True)

In [15]:
for i, df in enumerate(metadata_dfs, start=1):
    temp_df = df.astype(str)

    print(f"Meta{i} duplicate rows:", temp_df.duplicated().sum())

Meta1 duplicate rows: 0
Meta2 duplicate rows: 0
Meta3 duplicate rows: 0
Meta4 duplicate rows: 0
Meta5 duplicate rows: 0
Meta6 duplicate rows: 0
Meta7 duplicate rows: 0
Meta8 duplicate rows: 0
Meta9 duplicate rows: 0
Meta10 duplicate rows: 0

In [16]:
import os

os.makedirs("/content/metadata_parquet", exist_ok=True)

for i, df in enumerate(metadata_dfs, 1):
    path = f"/content/metadata_parquet/meta{i}.parquet"
    df.to_parquet(path, index=False)
    print("Saved:", path)

Saved: /content/metadata_parquet/meta1.parquet
Saved: /content/metadata_parquet/meta2.parquet
Saved: /content/metadata_parquet/meta3.parquet
Saved: /content/metadata_parquet/meta4.parquet
Saved: /content/metadata_parquet/meta5.parquet
Saved: /content/metadata_parquet/meta6.parquet
Saved: /content/metadata_parquet/meta7.parquet
Saved: /content/metadata_parquet/meta8.parquet
Saved: /content/metadata_parquet/meta9.parquet
Saved: /content/metadata_parquet/meta10.parquet

In [17]:
api = HfApi()
repo_id = "Satyamkarn100/NeuraRec-Electronics"
for i in range(1, 11):
    local_path = f"/content/metadata_parquet/meta{i}.parquet"
    api.upload_file(
        path_or_fileobj=local_path,
        path_in_repo=f"raw/meta{i}.parquet",
        repo_id=repo_id,
        repo_type="dataset",
        commit_message=f"Upload cleaned metadata part {i}")

    print(f"Uploaded meta{i}.parquet")

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ata_parquet/meta1.parquet:  11%|#         | 15.9MB /  147MB

Uploaded meta1.parquet

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ata_parquet/meta2.parquet:  11%|#1        | 16.0MB /  145MB

Uploaded meta2.parquet

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ata_parquet/meta3.parquet:  11%|#1        | 15.9MB /  143MB

Uploaded meta3.parquet

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ata_parquet/meta4.parquet:  11%|#1        | 16.0MB /  141MB

Uploaded meta4.parquet

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ata_parquet/meta5.parquet:  17%|#7        | 24.0MB /  139MB

Uploaded meta5.parquet

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ata_parquet/meta6.parquet:  12%|#1        | 15.9MB /  134MB

Uploaded meta6.parquet

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ata_parquet/meta7.parquet:  12%|#2        | 16.0MB /  131MB

Uploaded meta7.parquet

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ata_parquet/meta8.parquet:  12%|#1        | 15.9MB /  134MB

Uploaded meta8.parquet

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ata_parquet/meta9.parquet:  12%|#2        | 15.9MB /  131MB

Uploaded meta9.parquet

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ta_parquet/meta10.parquet:  13%|#2        | 16.0MB /  126MB

Uploaded meta10.parquet