<a href="https://colab.research.google.com/github/satyamkarn100-ctrl/Neural-Recommendation-Personalization-Engine/blob/main/02_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
!pip install -q huggingface_hub
from huggingface_hub import hf_hub_download
from huggingface_hub import login
login()

In [ ]:
reviews_path = hf_hub_download(
    repo_id="Satyamkarn100/NeuraRec-Electronics",
    filename="raw/reviews.parquet",
    repo_type="dataset"
)

In [ ]:
reviews = pd.read_parquet(reviews_path)
print('Reviews Shape:',reviews.shape)

Reviews Shape: (15473536, 4)

In [ ]:
reviews.head()

                        user_id parent_asin  rating      timestamp
0  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B0047T79VS     3.0  1344406083000
1  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01HHURN3W     3.0  1408995743000
2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B00L0YLRUW     1.0  1439226089000
3  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B017T99JPG     5.0  1456772365000
4  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01LW71IBJ     5.0  1456772571000

In [ ]:
reviews['datetime'] = pd.to_datetime(
    reviews['timestamp'],unit='ms'
)

In [ ]:
print(reviews['parent_asin'].nunique())
print()
reviews.head(10)

368228

,user_id,parent_asin,rating,timestamp,datetime
0,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B0047T79VS,3.0,1344406083000,2012-08-08 06:08:03.000
1,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B01HHURN3W,3.0,1408995743000,2014-08-25 19:42:23.000
2,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B00L0YLRUW,1.0,1439226089000,2015-08-10 17:01:29.000
3,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B017T99JPG,5.0,1456772365000,2016-02-29 18:59:25.000
4,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B01LW71IBJ,5.0,1456772571000,2016-02-29 19:02:51.000
5,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B09S6Y5BRG,5.0,1541356831659,2018-11-04 18:40:31.659
6,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B07BHHB5RH,5.0,1565130879386,2019-08-06 22:34:39.386
7,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B07CML419K,5.0,1637522881041,2021-11-21 19:28:01.041
8,AGBFYI2DDIKXC5Y4FARTYDTQBMFQ,B013KPXNSW,5.0,1453856042000,2016-01-27 00:54:02.000
9,AGBFYI2DDIKXC5Y4FARTYDTQBMFQ,B08P3VMW76,5.0,1483327495000,2017-01-02 03:24:55.000

In [ ]:
meta_paths = []

for i in range(1, 11):
    path = hf_hub_download(
        repo_id="Satyamkarn100/NeuraRec-Electronics",
        filename=f"raw/meta{i}.parquet",
        repo_type="dataset"
    )
    meta_paths.append(path)

print("Downloaded:", len(meta_paths), "files")

Downloaded: 10 files

In [ ]:
meta = pd.concat(
    [pd.read_parquet(path) for path in meta_paths],
    ignore_index=True
)

print("Meta-Data Shape:", meta.shape)
meta.head()

Meta-Data Shape: (1610012, 10)

,main_category,title,average_rating,rating_number,features,description,store,categories,details,parent_asin
0,All Electronics,FS-1051 FATSHARK TELEPORTER V3 HEADSET,3.5,6,[],[Teleporter V3 The “Teleporter V3” kit sets a ...,Fat Shark,"[Electronics, Television & Video, Video Glasses]","{""Date First Available"": ""August 2, 2014"", ""Ma...",B00MCW7G9M
1,All Electronics,Ce-H22B12-S1 4Kx2K Hdmi 4Port,5.0,1,"[UPC: 662774021904, Weight: 0.600 lbs]",[HDMI In - HDMI Out],SIIG,"[Electronics, Television & Video, Accessories,...","{""Product Dimensions"": ""0.83 x 4.17 x 2.05 inc...",B00YT6XQSE
2,Computers,Digi-Tatoo Decal Skin Compatible With MacBook ...,4.5,246,[WARNING: Please IDENTIFY MODEL NUMBER on the ...,[],Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop ...","{""Brand"": ""Digi-Tatoo"", ""Color"": ""Fresh Marble...",B07SM135LS
3,AMAZON FASHION,NotoCity Compatible with Vivoactive 4 band 22m...,4.5,233,[☛NotoCity 22mm band is designed for Vivoactiv...,[],NotoCity,"[Electronics, Wearable Technology, Clips, Arm ...","{""Date First Available"": ""May 29, 2020"", ""Manu...",B089CNGZCW
4,Cell Phones & Accessories,Motorola Droid X Essentials Combo Pack,3.8,64,"[New Droid X Essentials Combo Pack, Exclusive ...",[all Genuine High Quality Motorola Made Access...,Verizon,"[Electronics, Computers & Accessories, Compute...","{""Product Dimensions"": ""11.6 x 6.9 x 3.1 inche...",B004E2Z88O

In [18]:
print("Metadata Shape:", meta.shape)
print("\nColumns:")
print(meta.columns.tolist())

print("\nData Types:")
print(meta.dtypes)

print("\nInfo:")
meta.info()

Metadata Shape: (1610012, 13)

Columns:
['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'store', 'categories', 'details', 'parent_asin', 'features_key', 'description_key', 'categories_key']

Data Types:
main_category       object
title               object
average_rating     float64
rating_number        int64
features            object
description         object
store               object
categories          object
details             object
parent_asin         object
features_key        object
description_key     object
categories_key      object
dtype: object

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1610012 entries, 0 to 1610011
Data columns (total 13 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   main_category    1610012 non-null  object
 1   title            1610012 non-null  object
 2   average_rating   1610012 non-null  float64
 3   rating_number    1610012 non-null  int64
 4   features         1610012 non-null  object
 5   description      1610012 non-null  object
 6   store            1600492 non-null  object
 7   categories       1610012 non-null  object
 8   details          1610012 non-null  object
 9   parent_asin      1610012 non-null  object
 10  features_key     1610012 non-null  object
 11  description_key  1610012 non-null  object
 12  categories_key   1610012 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 159.7+ MB

In [ ]:
meta.loc[meta["main_category"].isna(),["categories", "title"]].head(10)

,categories,title
9,"[Electronics, Car & Vehicle Electronics, Marin...","Fishfinder, Depth Finder Poly Sun Cover for 3""..."
91,"[Electronics, Car & Vehicle Electronics, Aviat...",AirClassics Flight Bag | ASA-BAG-FLT-1
149,"[Electronics, Computers & Accessories, Laptop ...",LOVEVOOK Laptop Backpack for Women Work Travel...
314,"[Electronics, Computers & Accessories, Laptop ...",Advocator Slim Business Backpack for Laptop Up...
368,"[Electronics, Computers & Accessories, Laptop ...",DHK Leather Backpack Vintage Laptop Bookbag fo...
434,"[Electronics, Computers & Accessories, Laptop ...",Leather 15.6 inch Laptop Backpack Hiking Campi...
504,"[Electronics, Camera & Photo, Underwater Photo...",DIVEROID Waterproof Phone Case – Easy to Use U...
647,"[Electronics, Portable Audio & Video, Portable...",Ultimate Ears MEGABLAST Portable Waterproof Wi...
748,"[Electronics, Car & Vehicle Electronics, Marin...",Simrad 000-14077-001 GO7 XSR Chartplotter/Fish...
978,"[Electronics, Computers & Accessories, Laptop ...","BAGEIRA Travel Backpack for Men Women, 15.6 La..."

In [ ]:
missing_mask_cat = meta['main_category'].isna()
meta.loc[missing_mask_cat,'main_category'] = meta.loc[
    missing_mask_cat,'categories'
].apply(lambda x: x[0]
        if isinstance(x,(list,tuple,np.ndarray)) and len(x)>0
        else np.nan)

In [ ]:
meta["main_category"].isna().sum()

np.int64(0)

In [ ]:
meta.loc[
    meta['store'].isna(),
 ['store','title','main_category','categories']].head(20)

,store,title,main_category,categories
170,None,1510X Projector Lamp Replacement for DELL (Hou...,Office Products,"[Electronics, Television & Video, Accessories,..."
496,None,Baccus Global Llc - V1 Rechargeable Spotlight ...,All Electronics,[]
790,None,iColor Blue 8.9 9.7 10 10.1 10.2 Inch Kids Tab...,Computers,[]
894,None,Composition Notebook Design Protective Decal S...,Computers,"[Electronics, Computers & Accessories, Laptop ..."
982,None,Bfun Union Jack Flag Silicone MacBook Pro Keyb...,Computers,"[Electronics, Computers & Accessories, Laptop ..."
1030,None,Retro Style Laptop VGA Web Camera Skype PC Cam,Computers,"[Electronics, Computers & Accessories, Compute..."
1039,None,"Soft Turntable for Vinyl Record Cleaner Brush,...",All Beauty,"[Electronics, Television & Video, Accessories,..."
1113,None,Doryum Anti Scratch 0.3mm Thin Tempered Glass ...,Computers,"[Electronics, Computers & Accessories, Tablet ..."
1150,None,Tegrin + Plus 2in1 Dandruff Shampoo and Condit...,Computers,[]
1597,None,New 3d 8gb Gold Bar flash drive Usb Flash Pen ...,Computers,"[Electronics, Computers & Accessories, Data St..."
1665,None,Las Vegas HD Video Tour (BLU-RAY DISC),All Electronics,[]
1881,None,Red lemon 9H Hardness Tempered Glass Screen Pr...,Computers,[]
1929,None,"Sunflower Stickers Pack for Water Bottle,Water...",Computers,[]
2259,None,"Layopo Screen E-reading Lamp, 2019 New Upgrade...",Computers,"[Electronics, Computers & Accessories, Compute..."
2310,None,Compaq Presario C300 C500 DC Power Jack Cable,Electronics,"[Electronics, Computers & Accessories, Compute..."
2480,None,X-group Premium Ultra Clear Scratch Resistant ...,Computers,"[Electronics, Computers & Accessories, Tablet ..."
2532,None,"Caison 13.3"" Laptop Sleeve Cross Body Case Bag...",Computers,[]
2691,None,Cute You are My Sunshine Stickers Pack 50pcs S...,Computers,[]
2807,None,YURBUDS Inspire Duro Earbuds BLUE,All Electronics,"[Electronics, Headphones, Earbuds & Accessorie..."
3021,None,Ishoppingdeals 12 Item Charger All Bundle for ...,Home Audio & Theater,[]

In [ ]:
meta.loc[
    meta['store'].isna(),
    'title'
].duplicated().sum()

np.int64(186)

In [ ]:
meta['features_key'] = meta['features'].apply(str)
meta['description_key'] = meta['description'].apply(str)
meta['categories_key'] = meta['categories'].apply(str)

In [ ]:
store_map = (
    meta[meta['store'].notna()]
    .groupby(['features_key', 'description_key', 'categories_key'])['store']
    .agg(lambda x: x.unique()[0] if x.nunique() == 1 else np.nan)
)

In [19]:
missing_mask = meta['store'].isna()

meta.loc[missing_mask, 'store'] = (
    meta.loc[missing_mask]
    .set_index(['features_key', 'description_key', 'categories_key'])
    .index
    .map(store_map)
)

In [20]:
meta.isna().sum()

main_category         0
title                 0
average_rating        0
rating_number         0
features              0
description           0
store              9479
categories            0
details               0
parent_asin           0
features_key          0
description_key       0
categories_key        0
dtype: int64

In [21]:
meta.drop(
    columns=['features_key', 'description_key', 'categories_key'],
    inplace=True,
    errors='ignore'
)

In [22]:
meta.isna().sum()

main_category        0
title                0
average_rating       0
rating_number        0
features             0
description          0
store             9479
categories           0
details              0
parent_asin          0
dtype: int64