<a href="https://colab.research.google.com/github/satyamkarn100-ctrl/Neural-Recommendation-Personalization-Engine/blob/main/02_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
!pip install -q huggingface_hub
from huggingface_hub import hf_hub_download
from huggingface_hub import login
login()

In [8]:
reviews_path = hf_hub_download(
    repo_id="Satyamkarn100/NeuraRec-Electronics",
    filename="raw/reviews.parquet",
    repo_type="dataset"
)

raw/reviews.parquet: reconstructing file:   0%|          |  0.00B /  313MB

raw/reviews.parquet: downloading bytes:           |  0.00B

In [9]:
reviews = pd.read_parquet(reviews_path)
print('Reviews Shape:',reviews.shape)

Reviews Shape: (15473536, 4)

In [10]:
reviews.head()

                        user_id parent_asin  rating      timestamp
0  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B0047T79VS     3.0  1344406083000
1  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01HHURN3W     3.0  1408995743000
2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B00L0YLRUW     1.0  1439226089000
3  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B017T99JPG     5.0  1456772365000
4  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01LW71IBJ     5.0  1456772571000

In [11]:
reviews['datetime'] = pd.to_datetime(
    reviews['timestamp'],unit='ms'
)

In [12]:
print(reviews['parent_asin'].nunique())
print()
reviews.head(10)

368228

,user_id,parent_asin,rating,timestamp,datetime
0,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B0047T79VS,3.0,1344406083000,2012-08-08 06:08:03.000
1,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B01HHURN3W,3.0,1408995743000,2014-08-25 19:42:23.000
2,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B00L0YLRUW,1.0,1439226089000,2015-08-10 17:01:29.000
3,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B017T99JPG,5.0,1456772365000,2016-02-29 18:59:25.000
4,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B01LW71IBJ,5.0,1456772571000,2016-02-29 19:02:51.000
5,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B09S6Y5BRG,5.0,1541356831659,2018-11-04 18:40:31.659
6,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B07BHHB5RH,5.0,1565130879386,2019-08-06 22:34:39.386
7,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B07CML419K,5.0,1637522881041,2021-11-21 19:28:01.041
8,AGBFYI2DDIKXC5Y4FARTYDTQBMFQ,B013KPXNSW,5.0,1453856042000,2016-01-27 00:54:02.000
9,AGBFYI2DDIKXC5Y4FARTYDTQBMFQ,B08P3VMW76,5.0,1483327495000,2017-01-02 03:24:55.000

In [2]:
meta_paths = []

for i in range(1, 11):
    path = hf_hub_download(
        repo_id="Satyamkarn100/NeuraRec-Electronics",
        filename=f"raw/meta{i}.parquet",
        repo_type="dataset"
    )
    meta_paths.append(path)

print("Downloaded:", len(meta_paths), "files")

raw/meta1.parquet: reconstructing file:   0%|          |  0.00B /  148MB

raw/meta1.parquet: downloading bytes:           |  0.00B

raw/meta2.parquet: reconstructing file:   0%|          |  0.00B /  145MB

raw/meta2.parquet: downloading bytes:           |  0.00B

raw/meta3.parquet: reconstructing file:   0%|          |  0.00B /  143MB

raw/meta3.parquet: downloading bytes:           |  0.00B

raw/meta4.parquet: reconstructing file:   0%|          |  0.00B /  142MB

raw/meta4.parquet: downloading bytes:           |  0.00B

raw/meta5.parquet: reconstructing file:   0%|          |  0.00B /  139MB

raw/meta5.parquet: downloading bytes:           |  0.00B

raw/meta6.parquet: reconstructing file:   0%|          |  0.00B /  134MB

raw/meta6.parquet: downloading bytes:           |  0.00B

raw/meta7.parquet: reconstructing file:   0%|          |  0.00B /  131MB

raw/meta7.parquet: downloading bytes:           |  0.00B

raw/meta8.parquet: reconstructing file:   0%|          |  0.00B /  134MB

raw/meta8.parquet: downloading bytes:           |  0.00B

raw/meta9.parquet: reconstructing file:   0%|          |  0.00B /  131MB

raw/meta9.parquet: downloading bytes:           |  0.00B

raw/meta10.parquet: reconstructing file:   0%|          |  0.00B /  126MB

raw/meta10.parquet: downloading bytes:           |  0.00B

Downloaded: 10 files

In [3]:
meta = pd.concat(
    [pd.read_parquet(path) for path in meta_paths],
    ignore_index=True
)

print("Meta-Data Shape:", meta.shape)
meta.head()

Meta-Data Shape: (1610012, 11)

,main_category,title,average_rating,rating_number,features,description,price,store,categories,details,parent_asin
0,All Electronics,FS-1051 FATSHARK TELEPORTER V3 HEADSET,3.5,6,[],[Teleporter V3 The “Teleporter V3” kit sets a ...,None,Fat Shark,"[Electronics, Television & Video, Video Glasses]","{""Date First Available"": ""August 2, 2014"", ""Ma...",B00MCW7G9M
1,All Electronics,Ce-H22B12-S1 4Kx2K Hdmi 4Port,5.0,1,"[UPC: 662774021904, Weight: 0.600 lbs]",[HDMI In - HDMI Out],None,SIIG,"[Electronics, Television & Video, Accessories,...","{""Product Dimensions"": ""0.83 x 4.17 x 2.05 inc...",B00YT6XQSE
2,Computers,Digi-Tatoo Decal Skin Compatible With MacBook ...,4.5,246,[WARNING: Please IDENTIFY MODEL NUMBER on the ...,[],19.99,Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop ...","{""Brand"": ""Digi-Tatoo"", ""Color"": ""Fresh Marble...",B07SM135LS
3,AMAZON FASHION,NotoCity Compatible with Vivoactive 4 band 22m...,4.5,233,[☛NotoCity 22mm band is designed for Vivoactiv...,[],9.99,NotoCity,"[Electronics, Wearable Technology, Clips, Arm ...","{""Date First Available"": ""May 29, 2020"", ""Manu...",B089CNGZCW
4,Cell Phones & Accessories,Motorola Droid X Essentials Combo Pack,3.8,64,"[New Droid X Essentials Combo Pack, Exclusive ...",[all Genuine High Quality Motorola Made Access...,14.99,Verizon,"[Electronics, Computers & Accessories, Compute...","{""Product Dimensions"": ""11.6 x 6.9 x 3.1 inche...",B004E2Z88O

In [ ]:
meta["price"] = pd.to_numeric(meta["price"], errors="coerce")

In [ ]:
def list_to_text(x):
  if x is None:
    return ""

  if isinstance(x,(list,np.ndarray)):
    if len(x) == 0:
      return ""
    return " ".join(map(str,x))

  return str(x)

meta["features"] = meta["features"].apply(list_to_text)
meta["description"] = meta["description"].apply(list_to_text)

In [ ]:
print(meta['features'].head().tolist())
print(meta['description'].head().tolist())

['', 'UPC: 662774021904 Weight: 0.600 lbs', 'WARNING: Please IDENTIFY MODEL NUMBER on the bottom of your Macbook. Only fits for model A2338/ A2289/ A2251 (Macbook Pro 13" w/ Touch Bar, 2022/2020 release). Extra Care Yet Not Bulky. Our skin is capable of protecting the surface of your Macbook from daily scratches, dust, oil, water and fingerprint. Your Macbook remains fresh some years later. Elegant Style. Our stylish design and printing tech give your Macbook a 360 degree decorative and impressive looking. Take it out and get tons of compliments. Easy Apply. Easy, bubble-free installation and goo-free removal. Installation guide is well documented in paper material and video format. 100% SATISFACTION GUARANTEED. We use best vinyl material and printing technology and offer premium service. Full refund is guaranteed if you are not satisfied with our product.', "☛NotoCity 22mm band is designed for Vivoactive 4 / Samsung Gear S3 Classic / S3 Frontier / Gear Live / Samsung Galaxy Watch 46mm / Huawei Watch GT / Tickwatch Pro / S2 / E2 / Pebble Classic / Time / Time Steel / Pebble 2 (Not Pebble steel) / Other Watches with 22mm lugs. ➹Wrist Size: Small size fits wrist: 6.49inches-8.46inches (165-215mm), Large size fits wrist: 7.28inches-9.25inches (185-235mm) ,Please measure your wrist and make sure the size before you purchase. ➹No Tool Needed: Quick Release Pin is easy to wear or remove. Bands made of high-quality soft Silicone material, Anti-sweat, soft and more comfortable to wear. Metal clasp locks onto your watch band interface precisely and securely, so it's not moving on the watch band. ➹Suitable for Many Occasions: Good for perspiration which is suitable for sports of various kinds. Such as, Running, Walking, Climbing, swimming, biking and others. Simple stripe design, suitable for daily life, study and work. ☎Any problem with the item you receive or any opinion, please don't hesitate to contact us, we will find the best solution to solve.", 'New Droid X Essentials Combo Pack Exclusive Package Incredible Value Worth $145!!! Includes all Genuine High Quality Motorola Made Accessories']
['Teleporter V3 The “Teleporter V3” kit sets a new level of value in the FPV world with Fat Shark renowned performance and quality. The fun of FPV is experienced firsthand through the large screen FPV headset with integrated NexwaveRF receiver technology while simultaneously recording onboard HD footage with the included “PilotHD” camera. The “Teleporter V3” kit comes complete with everything you need to step into the cockpit of your FPV vehicle. We’ve included our powerful 250mW 5.8Ghz transmitter, 25 degree FOV headset (largest QVGA display available), the brand new “PilotHD” camera with live AV out and all the cables, antennas and connectors needed.', 'HDMI In - HDMI Out', '', '', 'all Genuine High Quality Motorola Made Accessories, including Multimedia Station with HDMI technology, HDMI Cable and AC Wall Charger, Motorola Navigation / Music Vehicle Charging Mount Car Dock and Motorola 12v Vehicle Power Adapter Charger!']

In [ ]:
print(type(meta['features'].iloc[0]))
print(type(meta['description'].iloc[0]))

<class 'str'>
<class 'str'>

In [ ]:
reviews_asins = set(reviews['parent_asin'])
meta_asins = set(meta['parent_asin'])

matched_asins = reviews_asins.intersection(meta_asins)

In [ ]:
print("Total review rows:", len(reviews))
print("Unique products in reviews:", len(reviews_asins))
print("Unique products in metadata:", len(meta_asins))
print("Matched products:", len(matched_asins))

coverage = len(matched_asins)/len(reviews_asins)*100
print("Meta-data Coverage:",round(coverage,2),'%')

Total review rows: 15473536
Unique products in reviews: 368228
Unique products in metadata: 161002
Matched products: 52719
Meta-data Coverage: 14.32 %