<a href="https://colab.research.google.com/github/satyamkarn100-ctrl/Neural-Recommendation-Personalization-Engine/blob/main/02_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
!pip install -q huggingface_hub
from huggingface_hub import hf_hub_download
from huggingface_hub import login
login()

In [2]:
reviews_path = hf_hub_download(
    repo_id="Satyamkarn100/NeuraRec-Electronics",
    filename="raw/reviews.parquet",
    repo_type="dataset"
)

raw/reviews.parquet: reconstructing file:   0%|          |  0.00B /  313MB

raw/reviews.parquet: downloading bytes:           |  0.00B

In [3]:
reviews = pd.read_parquet(reviews_path)
print('Reviews Shape:',reviews.shape)

Reviews Shape: (15473536, 4)

In [4]:
reviews.head()

                        user_id parent_asin  rating      timestamp
0  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B0047T79VS     3.0  1344406083000
1  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01HHURN3W     3.0  1408995743000
2  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B00L0YLRUW     1.0  1439226089000
3  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B017T99JPG     5.0  1456772365000
4  AGCI7FAH4GL5FI65HYLKWTMFZ2CQ  B01LW71IBJ     5.0  1456772571000

In [5]:
reviews['datetime'] = pd.to_datetime(
    reviews['timestamp'],unit='ms'
)

In [6]:
print(reviews['parent_asin'].nunique())
print()
reviews.head(10)

368228

,user_id,parent_asin,rating,timestamp,datetime
0,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B0047T79VS,3.0,1344406083000,2012-08-08 06:08:03.000
1,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B01HHURN3W,3.0,1408995743000,2014-08-25 19:42:23.000
2,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B00L0YLRUW,1.0,1439226089000,2015-08-10 17:01:29.000
3,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B017T99JPG,5.0,1456772365000,2016-02-29 18:59:25.000
4,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B01LW71IBJ,5.0,1456772571000,2016-02-29 19:02:51.000
5,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B09S6Y5BRG,5.0,1541356831659,2018-11-04 18:40:31.659
6,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B07BHHB5RH,5.0,1565130879386,2019-08-06 22:34:39.386
7,AGCI7FAH4GL5FI65HYLKWTMFZ2CQ,B07CML419K,5.0,1637522881041,2021-11-21 19:28:01.041
8,AGBFYI2DDIKXC5Y4FARTYDTQBMFQ,B013KPXNSW,5.0,1453856042000,2016-01-27 00:54:02.000
9,AGBFYI2DDIKXC5Y4FARTYDTQBMFQ,B08P3VMW76,5.0,1483327495000,2017-01-02 03:24:55.000

In [7]:
meta_paths = []

for i in range(1, 11):
    path = hf_hub_download(
        repo_id="Satyamkarn100/NeuraRec-Electronics",
        filename=f"raw/meta{i}.parquet",
        repo_type="dataset"
    )
    meta_paths.append(path)

print("Downloaded:", len(meta_paths), "files")

raw/meta1.parquet: reconstructing file:   0%|          |  0.00B /  148MB

raw/meta1.parquet: downloading bytes:           |  0.00B

raw/meta2.parquet: reconstructing file:   0%|          |  0.00B /  145MB

raw/meta2.parquet: downloading bytes:           |  0.00B

raw/meta3.parquet: reconstructing file:   0%|          |  0.00B /  143MB

raw/meta3.parquet: downloading bytes:           |  0.00B

raw/meta4.parquet: reconstructing file:   0%|          |  0.00B /  142MB

raw/meta4.parquet: downloading bytes:           |  0.00B

raw/meta5.parquet: reconstructing file:   0%|          |  0.00B /  139MB

raw/meta5.parquet: downloading bytes:           |  0.00B

raw/meta6.parquet: reconstructing file:   0%|          |  0.00B /  134MB

raw/meta6.parquet: downloading bytes:           |  0.00B

raw/meta7.parquet: reconstructing file:   0%|          |  0.00B /  131MB

raw/meta7.parquet: downloading bytes:           |  0.00B

raw/meta8.parquet: reconstructing file:   0%|          |  0.00B /  134MB

raw/meta8.parquet: downloading bytes:           |  0.00B

raw/meta9.parquet: reconstructing file:   0%|          |  0.00B /  131MB

raw/meta9.parquet: downloading bytes:           |  0.00B

raw/meta10.parquet: reconstructing file:   0%|          |  0.00B /  126MB

raw/meta10.parquet: downloading bytes:           |  0.00B

Downloaded: 10 files

In [8]:
meta = pd.concat(
    [pd.read_parquet(path) for path in meta_paths],
    ignore_index=True
)

print("Meta-Data Shape:", meta.shape)
meta.head()

Meta-Data Shape: (1610012, 11)

,main_category,title,average_rating,rating_number,features,description,price,store,categories,details,parent_asin
0,All Electronics,FS-1051 FATSHARK TELEPORTER V3 HEADSET,3.5,6,[],[Teleporter V3 The “Teleporter V3” kit sets a ...,None,Fat Shark,"[Electronics, Television & Video, Video Glasses]","{""Date First Available"": ""August 2, 2014"", ""Ma...",B00MCW7G9M
1,All Electronics,Ce-H22B12-S1 4Kx2K Hdmi 4Port,5.0,1,"[UPC: 662774021904, Weight: 0.600 lbs]",[HDMI In - HDMI Out],None,SIIG,"[Electronics, Television & Video, Accessories,...","{""Product Dimensions"": ""0.83 x 4.17 x 2.05 inc...",B00YT6XQSE
2,Computers,Digi-Tatoo Decal Skin Compatible With MacBook ...,4.5,246,[WARNING: Please IDENTIFY MODEL NUMBER on the ...,[],19.99,Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop ...","{""Brand"": ""Digi-Tatoo"", ""Color"": ""Fresh Marble...",B07SM135LS
3,AMAZON FASHION,NotoCity Compatible with Vivoactive 4 band 22m...,4.5,233,[☛NotoCity 22mm band is designed for Vivoactiv...,[],9.99,NotoCity,"[Electronics, Wearable Technology, Clips, Arm ...","{""Date First Available"": ""May 29, 2020"", ""Manu...",B089CNGZCW
4,Cell Phones & Accessories,Motorola Droid X Essentials Combo Pack,3.8,64,"[New Droid X Essentials Combo Pack, Exclusive ...",[all Genuine High Quality Motorola Made Access...,14.99,Verizon,"[Electronics, Computers & Accessories, Compute...","{""Product Dimensions"": ""11.6 x 6.9 x 3.1 inche...",B004E2Z88O

In [9]:
print("Metadata Shape:", meta.shape)
print("\nColumns:")
print(meta.columns.tolist())

print("\nData Types:")
print(meta.dtypes)

print("\nInfo:")
meta.info()

Metadata Shape: (1610012, 11)

Columns:
['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'store', 'categories', 'details', 'parent_asin']

Data Types:
main_category      object
title              object
average_rating    float64
rating_number       int64
features           object
description        object
price              object
store              object
categories         object
details            object
parent_asin        object
dtype: object

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1610012 entries, 0 to 1610011
Data columns (total 11 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   main_category   1503678 non-null  object
 1   title           1610012 non-null  object
 2   average_rating  1610012 non-null  float64
 3   rating_number   1610012 non-null  int64
 4   features        1610012 non-null  object
 5   description     1610012 non-null  object
 6   price           1610012 non-null  object
 7   store           1600492 non-null  object
 8   categories      1610012 non-null  object
 9   details         1610012 non-null  object
 10  parent_asin     1610012 non-null  object
dtypes: float64(1), int64(1), object(9)
memory usage: 135.1+ MB

In [10]:
missing = pd.DataFrame({
    "Missing_Count": meta.isnull().sum(),
    "Missing_Percentage": (meta.isnull().sum() / len(meta) * 100).round(2)
})

missing.sort_values("Missing_Count", ascending=False)

                Missing_Count  Missing_Percentage
main_category          106334                6.60
store                    9520                0.59
title                       0                0.00
average_rating              0                0.00
rating_number               0                0.00
description                 0                0.00
features                    0                0.00
price                       0                0.00
categories                  0                0.00
details                     0                0.00
parent_asin                 0                0.00

In [11]:
print("Price available:", meta["price"].notna().sum())
print("Price missing:", meta["price"].isna().sum())

Price available: 1610012
Price missing: 0

### Missing Value Observations

- The `price` column has 67.30% missing values, making it unreliable for direct use without careful handling.
- `main_category` has 6.60% missing values, indicating some products lack category information.
- `store` has only 0.59% missing values and is mostly complete.
- Core recommendation-related fields such as `parent_asin`, `average_rating`, `rating_number`, `title`, `description`, and `categories` have no missing values.
- Since price is missing for most products, it should not be used as a primary feature unless an appropriate missing-value strategy is applied.

In [14]:
meta['price'] = meta['price'].replace(
    ['None','none','NULL','null',''],np.nan
)

# Convert price to numeric
meta['price'] = pd.to_numeric(meta['price'], errors='coerce')

# Missing indicator
meta['price_missing'] = meta['price'].isna().astype(int)

before = meta['price'].isna().sum()
print("Missing before:", before)

# Same title based median imputation
title_median = meta.groupby('title')['price'].transform('median')

meta['price'] = meta['price'].fillna(title_median)

after = meta['price'].isna().sum()
print("Missing after title-match fill:", after)
print("Recovered rows:", before - after)

Missing before: 1083563
Missing after title-match fill: 1075867
Recovered rows: 7696

In [19]:
meta.head()

,main_category,title,average_rating,rating_number,features,description,price,store,categories,details,parent_asin,price_missing
0,All Electronics,FS-1051 FATSHARK TELEPORTER V3 HEADSET,3.5,6,[],[Teleporter V3 The “Teleporter V3” kit sets a ...,NaN,Fat Shark,"[Electronics, Television & Video, Video Glasses]","{""Date First Available"": ""August 2, 2014"", ""Ma...",B00MCW7G9M,1
1,All Electronics,Ce-H22B12-S1 4Kx2K Hdmi 4Port,5.0,1,"[UPC: 662774021904, Weight: 0.600 lbs]",[HDMI In - HDMI Out],NaN,SIIG,"[Electronics, Television & Video, Accessories,...","{""Product Dimensions"": ""0.83 x 4.17 x 2.05 inc...",B00YT6XQSE,1
2,Computers,Digi-Tatoo Decal Skin Compatible With MacBook ...,4.5,246,[WARNING: Please IDENTIFY MODEL NUMBER on the ...,[],19.99,Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop ...","{""Brand"": ""Digi-Tatoo"", ""Color"": ""Fresh Marble...",B07SM135LS,0
3,AMAZON FASHION,NotoCity Compatible with Vivoactive 4 band 22m...,4.5,233,[☛NotoCity 22mm band is designed for Vivoactiv...,[],9.99,NotoCity,"[Electronics, Wearable Technology, Clips, Arm ...","{""Date First Available"": ""May 29, 2020"", ""Manu...",B089CNGZCW,0
4,Cell Phones & Accessories,Motorola Droid X Essentials Combo Pack,3.8,64,"[New Droid X Essentials Combo Pack, Exclusive ...",[all Genuine High Quality Motorola Made Access...,14.99,Verizon,"[Electronics, Computers & Accessories, Compute...","{""Product Dimensions"": ""11.6 x 6.9 x 3.1 inche...",B004E2Z88O,0

In [18]:
print(meta["main_category"].value_counts())

main_category
Computers                       418868
All Electronics                 376435
Camera & Photo                  223690
Cell Phones & Accessories       138237
Home Audio & Theater            106516
Industrial & Scientific          50555
Car Electronics                  27332
Tools & Home Improvement         24042
Amazon Home                      21299
Office Products                  21250
AMAZON FASHION                   18391
Sports & Outdoors                14581
Automotive                       13956
GPS & Navigation                  9339
Amazon Devices                    8484
Portable Audio & Accessories      8050
Musical Instruments               6668
Toys & Games                      3944
Health & Personal Care            3073
All Beauty                        1848
Arts, Crafts & Sewing             1496
Apple Products                    1078
Video Games                       1042
Books                              994
Baby                               797
Pet Supplies                       415
Software                           388
Amazon Fire TV                     248
Appliances                         236
Grocery                            195
Movies & TV                         75
Buy a Kindle                        67
Handmade                            34
Fire Phone                          31
Premium Beauty                       6
Gift Cards                           5
Collectible Coins                    5
Digital Music                        3
Magazine Subscriptions               2
Audible Audiobooks                   1
Unique Finds                         1
Collectibles & Fine Art              1
Name: count, dtype: int64

In [23]:
computers = meta[
    meta['main_category'].eq('Computers')
]
computers.head(50)

,main_category,title,average_rating,rating_number,features,description,price,store,categories,details,parent_asin,price_missing
2,Computers,Digi-Tatoo Decal Skin Compatible With MacBook ...,4.5,246,[WARNING: Please IDENTIFY MODEL NUMBER on the ...,[],19.99,Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop ...","{""Brand"": ""Digi-Tatoo"", ""Color"": ""Fresh Marble...",B07SM135LS,0
8,Computers,MOSISO Plastic Hard Shell Case & Keyboard Cove...,5.0,2,[],[],NaN,MOSISO,"[Electronics, Headphones, Earbuds & Accessorie...","{""Brand"": ""MOSISO"", ""Item Weight"": ""8 ounces"",...",B01MCZP7RF,1
10,Computers,Network Magic 4.0,3.3,14,"[Connect, Manage, and Secure Your Network, Sha...","[Product description, You try to connect your ...",NaN,Avanquest,"[Electronics, Computers & Accessories, Network...","{""Brand"": ""Avanquest"", ""Item model number"": ""4...",B000LV7P8I,1
13,Computers,eForCity Leather Case with Stand for 7-Inch Sa...,3.9,144,[Stop worrying about scratching your Samsung; ...,[Compatible With Samsung Galaxy Tab 2 P3100 7....,NaN,eForCity,"[Electronics, Computers & Accessories, Tablet ...","{""Standing screen display size"": ""7 Inches"", ""...",B00ABEQ6TY,1
14,Computers,Novelty Cute Cartoon USB 2.0 Flash Drive Data ...,4.7,198,[♥Best Gift♥-Catoon shape design different fro...,[This is a special usb stick that make as a cu...,8.98,Fire Stone,"[Electronics, Computers & Accessories, Data St...","{""Product Dimensions"": ""2.48 x 1.58 x 0.78 inc...",B07Y6K1PRB,0
17,Computers,BIPRA U3 2.5 inch USB 3.0 NTFS Portable Extern...,5.0,1,"[Storage capacity: 250GB, Formatted as NTFS fi...","[Bipra external USB 2.5"" portable size hard dr...",98.49,BIPRA,"[Electronics, Computers & Accessories, Data St...","{""Hard Drive"": ""250 GB usb 3"", ""Brand"": ""BIPRA...",B00VBTJCJE,0
18,Computers,WD Scorpio Blue 320GB Mobile SATA Hard Drive,4.0,37,[Low profile design to fit thin laptops and ta...,[WD Scorpio Blue 7 mm slim 2.5-inch SATA hard ...,NaN,Western Digital,"[Electronics, Computers & Accessories, Compute...","{""Hard Drive"": ""320 GB"", ""Brand"": ""Western Dig...",B007U1YGOS,1
20,Computers,"Gateway 15.6"" FHD Ultra Slim Budget Notebook, ...",4.1,15,"[【Processor】4 Core, 4 Threads, 4MB Cache, up t...","[Processor:, Intel® Pentium® Silver N5030 Proc...",189.99,Gateway,"[Electronics, Computers & Accessories, Compute...","{""Standing screen display size"": ""15.6 Inches""...",B0BYBG1PPD,0
26,Computers,HTC Vivid Black/Blue Perforated Cover,5.0,2,[Combines hard plastic material and soft silic...,[This Hybrid Protector Case is custom made for...,NaN,NextKin,[],"{""Manufacturer"": ""NextKin"", ""Is Discontinued B...",B00CDXINAQ,1
27,Computers,NVIDIA NVS 310 by PNY 1 GB DDR3 PCI Express Ge...,4.2,17,"[Chipset: NVIDIA NVS 310, Video Memory: 512MB ...",[This pre-owned or refurbished product has bee...,34.98,Amazon Renewed,"[Electronics, Computers & Accessories, Compute...","{""Product Dimensions"": ""5.7 x 2.5 x 2.8 inches...",B07QF5117Q,0
28,Computers,luo Cherry MX RGB Switch Mute Pink Switch Mute...,4.0,12,[This link is only the shaft and switches for ...,"[Cherry powder: a quiet version of cherry red,...",13.99,LUO,"[Electronics, Computers & Accessories, Compute...","{""Package Dimensions"": ""2.83 x 2.8 x 1.02 inch...",B094C5ZN1M,0
30,Computers,HP Elitebook 8560W New Replacement LCD Screen ...,4.7,4,[],[This is a compatible replacement screen for t...,63.33,HP,"[Electronics, Computers & Accessories, Monitors]","{""Manufacturer"": ""HP"", ""Best Sellers Rank"": {""...",B0178F72E6,0
35,Computers,Die-cut Vinyl decal sticker Snow White Holding...,4.5,11,[],[],NaN,Yawhevg,"[Electronics, Computers & Accessories, Laptop ...","{""Brand"": ""Yawhevg"", ""Item Weight"": ""1.02 ounc...",B00YQ6LZJ4,1
38,Computers,Brand New,4.1,8,[],[],NaN,L,"[Electronics, Computers & Accessories, Laptop ...","{""Manufacturer"": ""L"", ""Date First Available"": ...",B0084EZTLY,1
42,Computers,Centon Electronics Flash Memory Card (S1-SDHU1...,4.8,4,"[Memory for phone, tablets, and digital camera...","[Product Description, Centon 32GB SDHC UHS-1. ...",8.99,Centon,"[Electronics, Computers & Accessories, Compute...","{""RAM"": ""32 GB"", ""Brand"": ""Centon"", ""Series"": ...",B00FSTW88K,0
43,Computers,Galaxy Tab A 10.1 Case 2019 - Techcircle Slim ...,4.0,17,[❣ COMPATIBILITY: Specially designed for Samsu...,[❣❣ Techcircle Slim Lightweight Flip Stand Cas...,17.99,Techcircle,"[Electronics, Computers & Accessories, Tablet ...","{""Package Dimensions"": ""8.31 x 4.41 x 1.22 inc...",B08862M8VY,0
46,Computers,PNY 1TB PRO Elite Class 10 U3 V30 microSDXC Fl...,4.7,3380,"[Class 10, U3, V30 speed class performance wit...",[PNY PRO Elite Class 10 U3 V30 microSD Cards o...,109.99,PNY,"[Electronics, Computers & Accessories, Compute...","{""Brand"": ""PNY"", ""Series"": ""P-SDU1TBV32100PRO-...",B0BSQL7M51,0
48,Computers,VFENG Premium 4-in-1 3M Full Body Skin Sticker...,2.9,2,[],[],NaN,VFENG,"[Electronics, Computers & Accessories, Laptop ...","{""Brand"": ""VFENG"", ""Item model number"": ""SB3-G...",B08BJP9H1N,1
56,Computers,Dell Inspiron 17-5755 Laptop: AMD Quad-Core A8...,3.8,34,"[Dell Official Certified Refurbished Laptop, N...",[This Certified Refurbished product is tested ...,NaN,Amazon Renewed,"[Electronics, Computers & Accessories, Compute...","{""Standing screen display size"": ""17.3 Inches""...",B01F1JNIWG,1
61,Computers,iCasso Compatible with MacBook Pro 13 Inch Cas...,4.4,3503,[[IMPORTANT!!!]: ONLY Compatible with MacBook ...,[],27.99,iCasso,"[Electronics, Computers & Accessories, Laptop ...","{""Standing screen display size"": ""13 Inches"", ...",B08GFTPQ5B,0
69,Computers,120mm Aluminum Fan Filter Grills w/ Mounting S...,4.2,15,"[Set of 2 filters, Black mounting screws inclu...",[],NaN,OKGEAR,"[Electronics, Computers & Accessories, Compute...","{""Item Weight"": ""3.84 ounces"", ""Manufacturer"":...",B006NYHP82,1
70,Computers,"BENTOBEN iPad 9th Generation Case, iPad 8th Ge...",4.5,131,[【Designed for iPad 9th/8th/7th 10.2 inch】BENT...,[],NaN,BENTOBEN,"[Electronics, Computers & Accessories, Tablet ...","{""Standing screen display size"": ""10.2 Inches""...",B094JGVY16,1
77,Computers,"2020 Newest ASUS VivoBook 15.6"" FHD Laptop Com...",4.5,7,[[Upgrated by CUE] 12GB system memory for full...,[We sell computers with upgraded configuration...,NaN,ASUS,"[Electronics, Computers & Accessories, Compute...","{""Standing screen display size"": ""15.6 Inches""...",B08PQDHNG3,1
80,Computers,Acer Aspire High Performance 15.6 inch HD Lapt...,3.8,3,[],[],NaN,Acer,"[Electronics, Computers & Accessories, Compute...","{""Standing screen display size"": ""15.6 Inches""...",B07B4Z7G4Z,1
84,Computers,AC to DC Charger with 6 Feet (2 Meter) Long Co...,4.2,17,[AC to DC Charger with 6 Feet (2 Meter) Cord f...,[This AC-DC charger is for NABi 2 II NABI2-NV7...,NaN,Linkshare,"[Electronics, Computers & Accessories, Compute...","{""Brand"": ""Linkshare"", ""Item model number"": ""8...",B071GBD9RH,1
85,Computers,"GIGABYTE AERO 16 XE5-16"" 4K/UHD+ Samsung AMOLE...",3.3,10,[NVIDIA 30 Series GPU: NVIDIA GeForce RTX 3070...,[NVIDIA 30 Series GPU: NVIDIA GeForce RTX 3070...,1749.00,Gigabyte,"[Electronics, Computers & Accessories, Compute...","{""Standing screen display size"": ""16"", ""Max Sc...",B0BGMJX4RN,0
90,Computers,Adafruit FTDI Serial TTL-232 USB Cable [ADA70],4.5,67,"[FTDI cable, Translucent body with RX/TX LEDs,...",[Just about all electronics use TTL serial for...,24.63,Adafruit,"[Electronics, Computers & Accessories, Compute...","{""Brand"": ""Adafruit"", ""Connector Type"": ""USB T...",B00SK8LK1W,0
94,Computers,128MB TF Card Flash Memory Card TF Card +Adapt...,3.4,13,[You can share music and media between your PC...,[Smallest Removable Form Factor Forward Compat...,NaN,Gaayee,"[Electronics, Computers & Accessories, Compute...","{""Manufacturer"": ""CHENZHENSHIWULIANYUNSHIYE"", ...",B07GTCXRB6,1
99,Computers,Aruba Instant On AP11 2x2 WiFi Access Point | ...,4.4,119,[Aruba Instant On AP11 Indoor Access Points de...,[],109.99,Aruba a Hewlett Packard Enterprise company,"[Electronics, Computers & Accessories, Network...","{""Product Dimensions"": ""5.98 x 5.98 x 1.34 inc...",B098ZFMY25,0
101,Computers,Plugable USB 3.0 Sharing Switch for One-Button...,4.2,1325,[SIMPLE DEVICE SHARING - Compact design provid...,[],NaN,Plugable,"[Electronics, Computers & Accessories, Compute...","{""Operation Mode"": ""Toggle"", ""Operating Voltag...",B00JX3Q28Y,1
102,Computers,KHOMO - iPad 2 3 and 4 Generation Case - DUAL ...,4.5,2745,[✔️✔️ PLEASE check compatibility first - on th...,[KHOMO dual Series case choom introduces its b...,11.95,KHOMO,"[Electronics, Computers & Accessories, Tablet ...","{""Standing screen display size"": ""9.7 Inches"",...",B06XKRXLDR,0
105,Computers,Cookk Universal Folio Case for All 6.5-7.5 inc...,4.4,66,[Universal 6.5 - 7.5 inch smart pu leather tab...,"[Universal Folio Case, Compatibility:, Fits mo...",14.99,Cookk,"[Electronics, Computers & Accessories, Tablet ...","{""Package Dimensions"": ""8.2 x 7 x 0.9 inches"",...",B07GXM524L,0
106,Computers,SAYA Plastic Hard Shell for Mac Pro 13 w/o Tou...,4.8,6,[The Case you are clicking ONLY FITS for New M...,"[Material, Plastic and Polycarbonate., Functio...",NaN,SAYA,"[Electronics, Computers & Accessories, Laptop ...","{""Product Dimensions"": ""12.1 x 8.5 x 0.6 inche...",B076F845PK,1
108,Computers,Kenuco CAT5e UTP Booted Ethernet Patch Cable |...,5.0,1,[],[],NaN,KENUCO,"[Electronics, Computers & Accessories, Compute...","{""Brand"": ""KENUCO"", ""Connector Type"": ""RJ45"", ...",B01MEGA800,1
109,Computers,"BORIYUAN iPad Mini 6 Keyboard Case 2021, 7 Col...",4.3,1417,[Compatibility】- Boriyuan Stylish iPad Mini 6t...,[New iPad Mini 6 Keyboard Case 2021- Boriyuan ...,33.99,BORIYUAN,"[Electronics, Computers & Accessories, Tablet ...","{""Package Dimensions"": ""9.17 x 6.69 x 1.14 inc...",B0C3VJHW5Z,0
110,Computers,STARTO Basic Starter Kit for BBC Micro: Bit,5.0,2,[Students can use this Micro bit basic DIY kit...,[Kindly Note: 1.Micro: bit is not included.2.T...,NaN,STARTO,"[Electronics, Computers & Accessories, Compute...","{""Brand"": ""STARTO"", ""Item Weight"": ""7.1 ounces...",B009OZATLW,1
112,Computers,"Antenna, 2.4 GHz, 3 dB, SMA Male Connector",4.4,6,"[TRENDWARE TRENDNET 3 DB GAIN ANTENNA ADAPTOR,...","[TRENDWARE TRENDNET 3 DB GAIN ANTENNA ADAPTOR,...",NaN,Defender Security,"[Electronics, Computers & Accessories, Network...","{""Brand"": ""Defender Security"", ""Item model num...",B001DPP9RA,1
120,Computers,Kinmac 360° Protective Waterproof Laptop Case ...,4.8,8699,[Kinmac 360° super shockproof design: High reb...,[],21.38,Kinmac,"[Electronics, Computers & Accessories, Laptop ...","{""Package Dimensions"": ""15.5 x 9.75 x 1.8 inch...",B0BXKWKH5Z,0
122,Computers,ChasBete Surface 2017 New Pro and Surface Pro ...,4.2,30,[],[],NaN,ChasBete,"[Electronics, Computers & Accessories, Laptop ...","{""Package Dimensions"": ""13.46 x 10.39 x 0.47 i...",B07425SSMK,1
123,Computers,Joymax 4MP Ultra HD Webcam with Microphone - 3...,3.7,28,[],[],NaN,Joymax,"[Electronics, Camera & Photo, Video, Camcorders]","{""Standing screen display size"": ""4 Inches"", ""...",B08M6C8N9C,1
124,Computers,DIGITTRADE LS115-15 CariBlue Designer Notebook...,4.5,2120,[Dimensions of the neoprene notebook sleeve: 3...,[Notebook sleeves that are guaranteed to stand...,NaN,Digittrade,"[Electronics, Computers & Accessories, Laptop ...","{""Standing screen display size"": ""15.4 Inches""...",B071JM6J36,1
126,Computers,MonsDirect Case for Amazon Kindle Fire HD 8 & ...,4.6,390,"[Lightweight Fire HD 8 Case, only fit All-New ...","[Compatibility with:, Designed specifically fo...",18.99,MonsDirect,"[Electronics, Computers & Accessories, Tablet ...","{""Package Dimensions"": ""8.5 x 6.02 x 1.02 inch...",B093GWXVC4,0
139,Computers,"FLAGPOWER Webcam with Microphone, 1080P USB We...",4.0,44,[【1080P Auto Focus Webcam】Equipped with Full H...,[],NaN,FLAGPOWER,"[Electronics, Computers & Accessories, Compute...","{""Brand"": ""FLAGPOWER"", ""Hardware Platform"": ""L...",B08G48M1XH,1
144,Computers,InWin GT1 White ATX Mid Tower Computer Chassis...,4.2,32,[GT1 supports up to 3 high-end full size graph...,[GT1 supports up to 3 high-end full size graph...,NaN,IN WIN,"[Electronics, Computers & Accessories, Compute...","{""Number of USB 2.0 Ports"": ""2"", ""Brand"": ""IN ...",B00CMC9UB4,1
146,Computers,CoolBELL 15.6 Inch Laptop Sleeve Bag With Acce...,4.6,277,[The design of front pokect with small compart...,[CoolBELL bases on the cutting-edge of fashion...,NaN,CoolBELL,"[Electronics, Computers & Accessories, Laptop ...","{""Standing screen display size"": ""15.6 Inches""...",B01M14761Y,1
158,Computers,"Telustyle TV Antenna, Indoor Digital Amplified...",5.0,3,[EK-Supremacy EVO is a universal CPU water blo...,[EK-Supremacy EVO is an evolution of a EK-Supr...,NaN,EK Waterblocks,"[Electronics, Computers & Accessories, Compute...","{""Brand"": ""EK Waterblocks"", ""Item model number...",B00NZHRUU8,1
165,Computers,250GB Hard Disk Drive/HDD for Dell Inspiron 13...,4.5,3,[],[250GB Hard Disk Drive/HDD for Dell Inspiron 1...,NaN,Depending on inventory,"[Electronics, Computers & Accessories, Compute...","{""Package Dimensions"": ""7.5 x 4.6 x 2.5 inches...",B0087HFS9Q,1
166,Computers,Intel Dual Band Wireless-Ac 8265 w/Bluetooth 8...,4.6,618,[Product Type :Network Interface Controller Ad...,[INTEL WIFI WIRELESS-AC 8265 8265.NGWMG DUAL B...,20.00,Intel,"[Electronics, Computers & Accessories, Compute...","{""Wireless Type"": ""802.11n, 802.11b, 802.11g"",...",B01MZA1AB2,0
173,Computers,CUK HP Pavilion 17 Touch Gaming Notebook (i7-7...,3.0,6,[],[],NaN,Computer Upgrade King,"[Electronics, Computers & Accessories, Compute...","{""Standing screen display size"": ""17.3 Inches""...",B01H40LA6Q,1
176,Computers,KECOP Baby Pink USB Wire Keyboard with Rainbow...,4.5,27,[],[],23.99,KECOP,"[Electronics, Computers & Accessories, Compute...","{""Product Dimensions"": ""10 x 2 x 2.7 inches"", ...",B09H2JQD48,0

In [26]:
computers = meta[
    meta["main_category"] == "Computers"
].copy()

computers["categories_group"] = computers["categories"].apply(
    lambda x: " > ".join(map(str, x))
    if isinstance(x, (list, tuple, np.ndarray))
    else str(x)
)

In [29]:
computers_grouped = (
    computers
    .groupby("categories_group")["price"]
    .agg(
        total_products="count",
        unique_prices="nunique",
        min_price="min",
        median_price="median",
        max_price="max"
    )
    .reset_index()
)

display(computers_grouped)

,categories_group,total_products,unique_prices,min_price,median_price,max_price
0,,4436,1863,0.01,39.210,6999.00
1,Car & Vehicle Electronics > Vehicle Electronic...,0,0,NaN,NaN,NaN
2,Car & Vehicle Electronics > Vehicle Electronic...,0,0,NaN,NaN,NaN
3,Electronics > 12-Month Financing on Computers,1,1,219.99,219.990,219.99
4,Electronics > 2 in 1 PCs > Convertibles,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...
763,Electronics > iPad Air 2 & iPad mini 3 Accesso...,0,0,NaN,NaN,NaN
764,Electronics > iPad Air 2 & iPad mini 3 Accesso...,1,1,24.99,24.990,24.99
765,Electronics > iPad Air Accessories,0,0,NaN,NaN,NaN
766,Electronics > iPad mini Accessories > Cases,0,0,NaN,NaN,NaN
767,Electronics > samsung_tradein,6,6,6.62,42.925,59.00