<a href="https://colab.research.google.com/github/satyamkarn100-ctrl/Neural-Recommendation-Personalization-Engine/blob/main/04_baseline_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd
import numpy as np
!pip install -q huggingface_hub
from huggingface_hub import hf_hub_download
from huggingface_hub import HfApi
from huggingface_hub import login
login()

In [2]:
!pip install -U huggingface_hub

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.13/dist-packages (2.0.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (3.32.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (1.6.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (2.13.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (4.67.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub) (4.16.0)
Requirement already satisfied: anyio>=4.10 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2.0.0->huggingface_hub) (4.15.1)
Requirement already satisfied: httpcore2==2.13.0 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2.0.0->huggingface_hub) (2.13.0)
Requirement already satisfied: idna>=3.18 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2.0.0->huggingface_hub) (3.19)
Requirement already satisfied: truststore>=0.10 in /usr/local/lib/python3.13/dist-packages (from httpx2<3,>=2.0.0->huggingface_hub) (0.10.4)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore2==2.13.0->httpx2<3,>=2.0.0->huggingface_hub) (0.16.0)

In [3]:
# file_path_1 = hf_hub_download(
#     repo_id='Satyamkarn100/NeuraRec-Electronics',
#     filename='splits/test.parquet',
#     repo_type='dataset'
# )
file_path_2 = hf_hub_download(
    repo_id = 'Satyamkarn100/NeuraRec-Electronics',
    filename='splits/train.parquet',
    repo_type='dataset'
)
# file_path_3 = hf_hub_download(
#     repo_id = 'Satyamkarn100/NeuraRec-Electronics',
#     filename='splits/val.parquet',
#     repo_type='dataset'
# )

splits/train.parquet: reconstructing file:   0%|          |  0.00B /  576MB

splits/train.parquet: downloading bytes:           |  0.00B

In [4]:
# test =pd.read_parquet(file_path_1)
train = pd.read_parquet(file_path_2)
# val = pd.read_parquet(file_path_3)

In [5]:
train.head()

,user_id,parent_asin,rating,timestamp,datetime,user_idx,item_idx
0,AGUH4HQWSFAZEZWWJUPENAITOIAQ,B00000JBAT,5.0,929311804000,1999-06-13 22:10:04,1158914,301
1,AGH2EPQBBP4B6MQALE3IPQ3NGA6A,B00000JFIF,5.0,931879793000,1999-07-13 15:29:53,986979,327
2,AG4ZJVVMOHDHXHN3WXQWNZU3NNPQ,B00000JBAT,2.0,931886331000,1999-07-13 17:18:51,858313,301
3,AEUVZ6UTQAPJNFDG3JA2KMGOO32A,B00000J40U,5.0,931927874000,1999-07-14 04:51:14,345430,275
4,AHCXZZ6R4US43PBVXXVN47OTTVHQ,B00000J4FY,5.0,931985618000,1999-07-14 20:53:38,1344817,282

In [6]:
item_popularity = train['item_idx'].value_counts()
item_popularity

item_idx
204194    44755
170750    39016
230788    29823
137801    26180
254183    20876
          ...
303850        1
342313        1
300416        1
312285        1
303378        1
Name: count, Length: 317408, dtype: int64

In [7]:
top_50_items = item_popularity.head(50)
recommendations = top_50_items.head(10)
recommendations

item_idx
204194    44755
170750    39016
230788    29823
137801    26180
254183    20876
212428    19439
138923    17371
231545    15139
238140    14197
358186    13325
Name: count, dtype: int64

In [8]:
recommended_items = recommendations.index.tolist()

In [9]:
recommended_items

[204194,
 170750,
 230788,
 137801,
 254183,
 212428,
 138923,
 231545,
 238140,
 358186]

In [10]:
train = pd.read_parquet("hf://datasets/Satyamkarn100/NeuraRec-Electronics/splits/train.parquet")
val = pd.read_parquet("hf://datasets/Satyamkarn100/NeuraRec-Electronics/splits/val.parquet")
test = pd.read_parquet("hf://datasets/Satyamkarn100/NeuraRec-Electronics/splits/test.parquet")

In [11]:
test_user_items = test.groupby('user_idx')['item_idx'].apply(set)
test_user_items

user_idx
1          {359490, 361820}
2                  {322743}
5                  {308932}
7                  {325041}
8                  {275017}
                 ...
1641014    {316083, 336044}
1641015    {231545, 367676}
1641017            {340410}
1641021            {325468}
1641022            {361589}
Name: item_idx, Length: 575196, dtype: object